language: python
python:
  - "3.6"
  - "3.7"

# env:
#   jobs:
#     - REQ_VERSION: dev
#     # - REQ_VERSION: stable


install:
  - pip install -U "setuptools<49.2"  # avoid UserWarning
  - pip install -U pip
  - # pip install -r requirements_${REQ_VERSION}.txt
  - pip install atelier
  - pip install -e .
  - pip freeze

script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - inv install
  - inv prep test
  - export SPHINXOPTS="-j 1" ; inv bd
